name: Docker base image

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    env:
      USERNAME: joaoneto4
      PROJECT: base-image

    steps:
      - uses: actions/checkout@v3

      - name: Login GHCR
        run: echo "${{ secrets.GH_PATH }}" | docker login ghcr.io -u $USERNAME --password-stdin

      - name: Build image
        run: docker build . -t ghcr.io/$USERNAME/$PROJECT:latest

      - name: Push image
        run: docker push ghcr.io/$USERNAME/$PROJECT:latest
