name: Docker base image

on: 
    push

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        env:
          USERNAME: joaoneto4
          PROJECT: base-image
        steps:
            - uses: actions/checkout@v3
            
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
              
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            
            - name: Login to GitHub Container Registry
              run: echo "${{ secrets.GH_PATH }}" | docker login ghcr.io --username "$USERNAME" --password-stdin
