name: Docker base image

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login GHCR
        run: echo "${{ secrets.GH_PATH }}" | docker login ghcr.io -u joaoneto4 --password-stdin

      - name: Build
        run: docker build . -t ghcr.io/joaoneto4/base-image:latest

      - name: Push
        run: docker push ghcr.io/joaoneto4/base-image:latest
